### PR TITLE
added note to README

### PR DESCRIPTION
**Pull request by acmeyer**
For Issue #11

### CODE REVIEW

**Comment by sdhull** [comment]
FYI [it looks like](https://community.sendgrid.com/sendgrid/topics/what-do-the-inbound-parse-webhook-settings-actually-do) the "Spam Check" option simply adds some params (`spam_score` and `spam_report` params), and the "Send Raw" option is what makes all the normal params disappear.

**Comment by acmeyer** [comment]
Ok cool. Using the existing griddler setup I was having issues when either of these two settings were enabled on sendgrid. I assumed there are changes that could be made to better handle these settings, but in its current form I just wanted to provide a headsup to others. Those fixes should probably come as a different pr.

**Comment by gabebw** [comment]
Thanks! Merged.

**Comment by gabebw** [comment]
Oops, hit "submit" too fast. I rebased and merged this as a5be715fd6752d370aec027e1d743596e4a396d2.

**Pull request closed without merging**
