### PR TITLE
Test for pr 24

### PR DESCRIPTION
**Pull request by vgoodman**
New PR, since my test was failing with the changes from PR https://github.com/thoughtbot/griddler-sendgrid/pull/24 due to different placement of quotation marks and angle brackets.

### CODE REVIEW

**Comment by tcollier** [comment]
I just opened up https://github.com/thoughtbot/griddler-sendgrid/issues/27 before seeing your PR. When I pull your branch in locally, it fixes my problem! Thanks for taking the time to contribute to this gem.

**Comment by wingrunr21** [comment]
@vgoodman would you mind rebasing both of those commits together into a single commit? Once that's done I'll merge this

**Comment by vgoodman** [comment]
@wingrunr21, done!

**Comment by tcollier** [comment]
Thanks for the fix! Will this result in a new release of the gem?

**Comment by wingrunr21** [comment]
Yep, released in v1.0.1

**Comment by nickrivadeneira** [comment]
This seems to have broken 10 out of 12 tests for me, tested on Ubuntu and Mac

**Comment by wingrunr21** [comment]
This release has been out for nearly a year? If there are bugs please submit a PR.

**Comment by nickrivadeneira** [comment]
Yup, haven't upgraded the gem in the past year. Started work on it to add support for Sendgrid's spam check, but ran into test failures. See: https://circleci.com/gh/nickrivadeneira/griddler-sendgrid/1 (that is a build of the latest commit on `master`).

I'm working on a fix right now, but the fix is to revert the work that was done here. Since there were multiple people that said this solved their issue, I'm a bit hesitant to do that.

Separately, thoughts on setting CI up to run as a requirement for PR merges? This could help prevent releases with broken builds.

**Comment by wingrunr21** [comment]
Sure, I'll set up Travis

**Comment by nickrivadeneira** [comment]
@wingrunr21 :+1: 

I opened a PR as promised - #30

**Comment by wingrunr21** [comment]
Thanks.

I'm not 100% sure this PR should be reverted. The change introduced here definitely solved an issue for a few people. Did you determine why the old code works now? Different version of `mail`?

**Comment by nickrivadeneira** [comment]
@wingrunr21 Looks like this was merged not too long after this PR was originally written: mikel/mail#1103. It was released as of `mail` v2.7.0 on 10/31/17: https://github.com/mikel/mail/blob/2-7-stable/CHANGELOG.rdoc#version-270-2017-10-31.

I wonder if there were some changes in `mail` that resulted in incompatibility with the changes in this PR.

**Comment by wingrunr21** [comment]
Ok cool. That makes sense. I may bump this to `v1.1.0` so that I can set a minimum version of `mail` in the gemspec.

**Pull request merged**
